export default function ReportFooter() {

  return (

    <div
      className="
        mt-12
        pt-6
        border-t-2
        border-pink-200
      "
    >

      <div
        className="
          flex
          justify-between
          items-end
        "
      >

        <div>

          <p className="text-gray-500 text-sm">
            Generated by Mom's Care
          </p>

          <p className="text-gray-500 text-sm">
            Maternal Healthcare Management System
          </p>

        </div>

        <div className="text-center">

          <div
            className="
              w-48
              border-b
              border-black
              mb-2
            "
          ></div>

          <p className="font-semibold">
            Doctor's Signature
          </p>

        </div>

      </div>

    </div>

  );

}